package com.jobseeker.cluedetectivenotes.model.card;

public enum DefaultCard {
    SCARLET, MUSTARD, WHITE, GREEN, PEACOCK, PLUM,
    CANDLESTICK, KNIFE, LEAD_PIPE, REVOLVER, ROPE, WRENCH,
    BATHROOM, STUDY, GAME_ROOM, GARAGE, BEDROOM, LIVING_ROOM, KITCHEN, YARD, DINING_ROOM
}
